// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenTungSon999.Migrations
{
    [DbContext(typeof(NguyenTungSon999Context))]
    [Migration("20211215064520_NTS0999")]
    partial class NTS0999
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NguyenTungSon999.CompanyNTS999", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyNTS999");
                });

            modelBuilder.Entity("NguyenTungSon999.NTS0999", b =>
                {
                    b.Property<string>("NTSId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NTSGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NTSName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NTSId");

                    b.ToTable("NTS0999");
                });
#pragma warning restore 612, 618
        }
    }
}
